#!/usr/bin/env bash

# regex to validate in commit msg
commit_regex='([A-Z]{1,}-[0-9]{1,}\s.+|Merge.*|Version Bump.*)'
error_msg="Aborting commit. Your commit message is missing either a Jira Issue ('PROJ-99') or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi