#!/bin/bash
installDirectory=~/Library/Developer/Xcode/Templates/Project\ Templates/
mkdir -p "${installDirectory}"
cp -R "Surf Base Application.xctemplate" "${installDirectory}"
cp -R "Surf MVP Application.xctemplate" "${installDirectory}"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Application"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Library/BaseClasses"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Library/Extensions"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Library/Protocols"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Library/Reusable Layer"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Library/Utils"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Models/Entry"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Models/Entity"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Resources/Constants"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Resources/Fonts"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Resources/Images"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Resources/Strings"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Screens"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Services"
mkdir -p "${installDirectory}/Surf MVP Application.xctemplate/Third Party"