platform :ios, '10.0'

inhibit_all_warnings!

def utils
    pod 'SwiftGen', '~> 6.1.0'
    pod 'SwiftLint', '~> 0.30.1'
end

def common_pods
    utils
    # Put your pods here
end

target 'Unicredit' do

    use_frameworks!

    common_pods
end


target 'UnicreditDebug' do
    use_frameworks!

    common_pods
end